apiVersion: apps/v1
kind: Deployment
namespace: {{.Values.namespace}}
metadata:
  name: consumer2
  namespace: {{.Values.namespace}}
spec:
  replicas: {{.Values.worker2Replicas}}
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: arguez/python-consumer:basic
        imagePullPolicy: Always
        resources:
          requests:
            cpu: {{.Values.worker2CPU}}
          limits:
            cpu: {{.Values.worker2CPU}}
        env:
        - name: DNS_NAMESPACE
          value: {{.Values.namespace}}
        - name: STRESS_SIZE
          value: "{{.Values.stressSize}}"
        - name: POOL_SIZE
          value: "{{.Values.poolSize2}}"
      priorityClassName: {{.Values.priorityClass}}
